version: "3.3"
services:
    app:
        build: .
        volumes:
            - .:/todo_app_django
        ports:
            - 8000:8000
        image: app:todo-django
        container_name: todo_django_container
        command: python manage.py runserver 0.0.0.0:8000

